type: map
required: true
mapping:
  'custom':
    type: any
    required: false

  'import':
    type: seq
    required: false
    sequence:
      - type: str
        required: true
  'ignore':
    type: seq
    required: false
    sequence:
      - type: str
        required: true
  'require':
    type: seq
    required: false
    sequence:
      - type: any
        required: true
  'control':
    type: map
    required: true
    mapping:
      'event': &optional_hash_with_string_values
        type: map
        required: false
        mapping:
          =:
            type: str
            required: true
      'mouse':
        type: map
        required: true
        mapping:
          'grab': &required_string
            type: str
            required: true
          =: *required_string
      'keyboard': *optional_hash_with_string_values
      'action': *optional_hash_with_string_values
      'keyboard_action': *optional_hash_with_string_values
  'script':
    type: map
    required: false
    mapping:
      'before': &script
        type: seq
        required: false
        sequence:
          - type: str
            required: true
      'after': *script
  'status':
    type: map
    required: false
    mapping:
      =:
        type: map
        required: true
        mapping: &status_barlet
          'params': &optional_hash
            type: map
            required: false
            mapping:
              =:
                type: any
          'script':
            type: str
            required: false
          'label':
            type: str
            required: false
          'refresh':
            type: int
            required: false
            range:
              min: 0
          'control':
            type: map
            required: false
            mapping:
              'event': *optional_hash_with_string_values
              'action': *optional_hash_with_string_values
              'mouse_action':
                type: map
                required: false
                mapping:
                  'left_click': &optional_string
                    type: str
                    required: false
                  'wheel_click': *optional_string
                  'right_click': *optional_string
                  'wheel_up': *optional_string
                  'wheel_down': *optional_string
                  'wheel_left': *optional_string
                  'wheel_right': *optional_string
  'display':
    type: map
    required: true
    mapping:
      'bar':
        type: str
        required: true
        enum: [top, bottom]
      'font':
        type: str
        required: true
      'border':
        type: int
        required: true
        range:
          min: 0
      'color':
        type: map
        required: true
        mapping:
          'desktop':
            type: str
            required: true
            pattern: '/^#\h{6}$/'
          'normal': &required_color_tuple
            type: str
            required: true
            pattern: '/^#\h{6} #\h{6} #\h{6}$/'
          'focus': *required_color_tuple
          =: *required_color_tuple
      'refresh':
        type: int
        required: false
        range:
          min: 0
      'column':
        type: map
        required: true
        mapping:
          'mode':
            type: str
            required: true
            enum: [default, stack, max]
          'rule':
            type: str
            required: true
      'client':
        type: map
        required: true
        mapping:
          =:
            type: seq
            required: true
            sequence:
              - type: str
                required: true
      'status':
        type: seq
        required: false
        sequence:
          - type: map
            required: false
            mapping:
              =:
                type: map
                required: false
                mapping: *status_barlet
