#!/usr/bin/ruby -w
# periodically print date and load average to the bar

$: << File.dirname(__FILE__)
require 'wmii'

DELAY = 1

WM = Wmii.instance

WM.remove '/bar/status'
WM.create '/bar/status'
WM.write '/bar/status/colors', ENV['WMII_NORMCOLORS']

while WM.write('/bar/status/data', Time.now.to_s << " " << `uptime`.scan(/\d+\.\d+/).join(' '))
  sleep DELAY
end
