#!/usr/bin/ruby -w
# periodically print date and load average to the bar

$: << File.dirname(__FILE__)
require 'wmii'

DELAY = 1

WM = Wmii.instance

system('wmiir remove /bar/status') && sleep(DELAY * 2)
system 'wmiir create /bar/status'
WM.write '/bar/status/colors', ENV['WMII_NORMCOLORS']

while WM.write('/bar/status/data', Time.now.to_s << " " << `uptime`.scan(/\d+\.\d+/).join(' '))
	sleep DELAY
end
