#!/usr/bin/ruby
# This is an interactive Ruby shell for wmiirc.
# - Access & manipulate wmii via the *W* constant.
# - Press the TAB key for command completion.
=begin
  Copyright 2006 Suraj N. Kurapati

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation; either version 2
  of the License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
=end


require 'rdoc/usage'

RDoc::usage_no_exit


$:.unshift File.dirname(__FILE__)
require 'wm'

W = Wmii.new


require 'irb'
require 'irb/completion'

IRB.start __FILE__
