control:
  action:

    action_menu: |
      if choice = key_menu(actions, 'action:', :action)
        action choice
      end

    reload: |
      # reload this wmii configuration
      Wmiirc::Loader.reload

      # restart the system tray applet
      spawn 'witray'

    clear: |
      system 'killall', 'witray',
        # the "restore session" feature in these browsers does
        # not work unless their entire process group is killed
        'opera',
        'firefox', 'firefox-bin',
        'chromium', 'chromium-browser',
        'thunderbird', 'thunderbird-bin'

      clients.each {|c| c.kill rescue nil }

    kill: |
      # kill the window manager only; do not touch the clients!
      fs.ctl.write 'quit'

    quit: |
      # kill both clients and window manager
      action 'clear'
      action 'kill'
